# -*- coding: utf-8 -*-
from models import send_mail

from models import (
    REG_THANKS_TEMPLATE,
    ORDER_CANCELED_TEMPLATE,
    ORDER_NEW_TEMPLATE,
    ORDER_AWAIT_PAYMENT_TEMPLATE,
    ORDER_COMPLETING_TEMPLATE,
    ORDER_DELIVERING_TEMPLATE,
    ORDER_DONE_TEMPLATE,
    ORDER_CARD_AWAIT_PAYMENT_TEMPLATE,
    ORDER_PAID_AWAIT_COMPLETING_TEMPLATE,
    ORDER_AWAIT_APPROVAL_TEMPLATE,
    ORDER_CARD_CANCELED_UNPAID_TEMPLATE,
)
